###################################################################################
#
#                                   配置文件
#
###################################################################################
#druid数据源
spring:
  #json日期格式化,转换前端json的日期
  jackson:
    #字符串格式
    date-format: yyyy-MM-dd
    #时区设置
    time-zone: GMT+8
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: cwd1995224920
    url: jdbc:mysql://localhost:3306/wxdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #JPA配置
#  jpa:
#    hibernate:
      #更新或者 创建数据表(数据库没有表时自动创建)
#      ddl-auto: update
    #控制台显示sql
#    show-sql: true
  #最大文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
#服务器配置
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 100MB
#mybatis配置
mybatis:
  type-aliases-package: com.cwd.Entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#debug模式:控制台打印详细的自动配置信息
debug: false

